//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rust.Properties
{
    using System.Resources;
    using System.Globalization;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings and other resources.
    /// </summary>
    internal static class Resources
    {
        private static readonly ResourceManager resourceManager = new ResourceManager(typeof(Resources));
        private static CultureInfo cultureInfo = CultureInfo.CurrentUICulture;

        /// <summary>
        /// Gets the cached ResourceManager instance used by this class.
        /// </summary>
        internal static ResourceManager ResourceManager => resourceManager;

        /// <summary>
        /// Gets or sets the culture for resource lookups using this strongly typed resource class.
        /// </summary>
        internal static CultureInfo Culture
        {
            get => cultureInfo;
            set => cultureInfo = value ?? throw new ArgumentNullException(nameof(value));
        }
    }
}

